### PR TITLE
Support for PHP 8.0

### PR DESCRIPTION
**Pull request by martinvenus**

### CODE REVIEW

**Comment by martinvenus** [comment]
https://github.com/Kdyby/CodingStandard/pull/5

**Comment by KacerCZ** [comment]
It will not be that easy - tests under PHP 8.0 fail in `AbstractRedisTestCase::threadStress()` because it fails to parse source.
PHP 8.0 changes how namespaces are tokenized: https://wiki.php.net/rfc/namespaced_names_as_token

**Comment by KacerCZ** [comment]
I made PR #100 where all tests pass.

**Comment by martinvenus** [comment]
Good job! Thank you very much. Closing this PR.

**Pull request closed without merging**
