### PR TITLE
Fixed reading extension config for session (RedisExtension.php)

### PR DESCRIPTION
**Pull request by zabous**
Merge - Merges dataset. Left has higher priority than right one.
Left must be taken from config file

### CODE REVIEW

**Comment by peldax** [comment]
Thank you.

**Review by VBoss — APPROVED** [review]

**Comment by Jakub-Fajkus** [comment]
This PR was reverted in https://github.com/Kdyby/Redis/pull/117. 
I cannot understand why this PR was created in the first place. The code does the exact opposite of what the PR description says. Because of this PR, the neon configuration was not used and that resulted in failed tests.

**Comment by peldax** [comment]
@Jakub-Fajkus I had the issue described in #109 and this "fix" solved it. However, today after upgrading to 6.1.1 everything works alright. It seems there was some other configuration issue, but I do not recall changing anything.

**Comment by jaroslavlibal** [comment]
@Jakub-Fajkus I'm not saying anything about the original fix (I haven't checked its details), but the 6.1.1 reintroduced the "Redis server went away" RedisException for us. So there will probably need to be some more work done. I'd like to help, but I don't know how. Versions lower than 6.0 worked fine.

**Comment by Jakub-Fajkus** [comment]
@peldax  @jaroslavlibal 
I've created a fix, see https://github.com/Kdyby/Redis/pull/119. Could you try it somewhere and confirm that the issues are gone? 
The duplicated configuration should not be needed anymore.

**Pull request merged**
