### PR TITLE
Add support for PHP 7.4

### PR DESCRIPTION
**Pull request by martinvenus**

### CODE REVIEW

**Comment by KacerCZ** [comment]
Add PHP 7.4 also to Travis configuration, please.

**Comment by martinvenus** [comment]
I really tried to fix tests on PHP 7.4, but I'm not able to do it. Is someone here who is able to do it please? :)

**Comment by VBoss** [comment]
There is reason why Nette/Tester is in that low version and that reason is why tests fails. Change it back and then fix problems with 7.4 if there are any. 

Also as it is for now, 7.4 is still not stable release so you can put it in allowed failures.

**Comment by martinvenus** [comment]
Done. Thanks.

**Comment by martinvenus** [comment]
Could you pls merge this PR please?

**Comment by martinvenus** [comment]
Is there anything more I can do for merging this PR?

**Comment by VBoss** [comment]
To be honest I was hoping at least some tests would pass 🙂. As it is right now, you can install Kdyby/Redis to your php7.4 application with `--ignore-platform-reqs` and that is same functionality as this PR.
Even if I would merge it I cannot release new tag with support of PHP7.4. because non of test are passing. Right now I dont know if it is because of old Nette/Tester or PHP7.4 stuff. If you want to help me, try fixing one test or at least describe why tests dont pass.

**Comment by martinvenus** [comment]
All test failing because of old Nette tester. 

I tried to fix tests in my local branch: https://github.com/martinvenus/Redis/pull/1 (I'm not able to fix 3 tests). You can see at Travis (https://travis-ci.org/martinvenus/Redis/builds/621287974) that "only" 3 tests are failing.

Maybe, someone is able to fix these 3 tests...

**Comment by KacerCZ** [comment]
Let's split this PR into smaller ones - one for fixing coding style, one for upgrade of Nette Tester and one that enables PHP 7.4 in package and CI.

**Comment by VBoss** [comment]
Splitted and done, thanks to all! Release - https://github.com/Kdyby/Redis/releases/tag/v5.1.0

**Pull request closed without merging**
