### PR TITLE
Fixed coding style

### PR DESCRIPTION
**Pull request by KacerCZ**

### CODE REVIEW

**Comment by VBoss** [comment]
If you are finished with this PR, assing me and I will merge it.

**Comment by KacerCZ** [comment]
This PR is ready.
I can't assign you so I've added you as reviewer.

**Comment by VBoss** [comment]
Great, thank you! After you are finished with other PRs assing me as reviewer too and lets merge all the things :)

**Comment by KacerCZ** [comment]
Thank you.

**Pull request merged**
