### PR TITLE
Support for PHP 7.4

### PR DESCRIPTION
**Pull request by KacerCZ**
Allow installation on PHP 7.4
Fixed notices
Run tools on PHP 7.4

### CODE REVIEW

**Comment by KacerCZ** [comment]
Travis failed only for PHP 7.4 with lowest dependency versions.
Nette utils 2.5 emit deprecation message under PHP 7.4.

**Comment by KacerCZ** [comment]
@VBoss Please review.
Nette utils 2.5 does not support PHP 7.4 so deprecation warning is kinda expected.

**Comment by VBoss** [comment]
I was looking at this and thinking about limiting utils only to 3.0. Enought time and releases passed, so could you please try removing 2.4 version of utils from composer, if all pases I will merge it and adress it in release properly.

**Comment by VBoss** [comment]
well, it would be nice to drop 2.4 dependencies eventualy, but not now. Drop last commit and we can merge it.

**Comment by KacerCZ** [comment]
I've fixed detection of nette/http 2.4 vs 3.0 in tests.
Let's see if all will pass.

**Comment by KacerCZ** [comment]
OK, tests are now passing.

**Comment by VBoss** [comment]
Great, thanks!

**Comment by JakubBarta** [comment]
Good job! Thank you!

**Comment by VBoss** [comment]
@KacerCZ great work on last PRs, meet me anytime at https://www.meetup.com/Pehapkari-Brno and I will give you `PHP 6 certified engineer` or `Proffesional Cache deleter` t-shirt :)

**Pull request merged**
